import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {JSDOM} from 'jsdom';
import {indexedDB} from 'fake-indexeddb';
import * as store from '../lib/visual-storage.mjs';
globalThis.indexedDB=indexedDB;
const asset=new Blob(['original pixels'],{type:'image/png'});
for(let i=0;i<2;i++)await store.saveProduct({id:'product-'+i,name:'منتج '+i,description:'سفر العائلة',fidelity:'exact',image:asset,reference:asset});
const products=await store.listProducts();assert.equal(products.length,2);assert.equal(await products[0].image.text(),'original pixels');assert.equal(products[0].fidelity,'exact');
const html=fs.readFileSync('index.html','utf8'),dom=new JSDOM(html,{url:'http://localhost',runScripts:'outside-only'}),win=dom.window,ctx=dom.getInternalVMContext();
win.store=store;win.structuredClone=structuredClone;win.URL.createObjectURL=()=> 'blob:qa';win.URL.revokeObjectURL=()=>{};
vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],ctx);
const controller=fs.readFileSync('lib/visual-studio.mjs','utf8').replace(/^import .*;\n/gm,'').replace('export function splitIdeas','function splitIdeas');vm.runInContext('(function(){'+controller+'})()',ctx);
const brain={name:'نجوب',product:'منظم سفر',customer:'العائلة'};win.localStorage.setItem('brain',JSON.stringify(brain));
const plan='# خطة نجوب\n\n## اليوم الأول\nالمنصة: Instagram\nالفكرة: رحلة الأسرة\n\n## اليوم الثاني\nالهدف: الوعي\nالفكرة: ترتيب الحقيبة\n\n## اليوم الثالث\nالمنصة: Instagram\nالفكرة: منظم سفر العائلة';
vm.runInContext("current='content';renderResult("+JSON.stringify(plan)+")",ctx);
assert.equal(win.document.querySelectorAll('#contentCards article').length,3);
await win.document.querySelectorAll('#contentCards button')[2].onclick();assert.ok(win.document.getElementById('visualSource').textContent.startsWith('## اليوم الثالث'));
assert.equal(win.document.getElementById('productFidelity').value,'exact');assert.ok(![...Array(win.localStorage.length)].some((_,i)=>win.localStorage.getItem(win.localStorage.key(i)).includes('original pixels')));
dom.window.close();console.log('PASS V0.7 M1: multiple product Blobs, default exact fidelity, Content cards and direct Day 3 handoff');
